Homework #2
yarmkhlv/2024-2-VK-EDU-Frontend-Y-Mikhailov pull request #2
Opened 2024-09-29 09:16 UTC by yarmkhlv

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:

-Развернут проект на Vite
-Сверстано окно чата с юзером
-Добавлен функционал отправки сообщений с использованием LocalStorage для сохранения истории

2024-09-29 12:22 UTC, sh4rkizz requested changes
Классно реализовал подгрузку иконок, чтобы не грузить весь спрайт, предложенный в домашке

vite немного не мой стек, поэтому постарался отписать функционально

2024-09-29 12:22 UTC, sh4rkizz commented on simple-chat/index.html
> +          </div>
предлагаю сделать больше отступы по бокам для сообщений [на скрине 16px]

![изображение](https://github.com/user-attachments/assets/9e3b4431-7237-4b54-ac69-f372d049be67)

2024-09-29 12:22 UTC, sh4rkizz commented on simple-chat/index.html
> +          </div>
также немного предлагаю поработать с контрастом, на белом бэкграунде очень синие блоки бьют по глазам
а блоки собеседника, которые белые, наоборот плохо видно

2024-09-29 12:22 UTC, sh4rkizz commented on simple-chat/src/js/eventListeners.js
> +});
Предлагаю доработать функционал собеседника - чтобы через 0.5 - 1s после отправляемого мной сообщения он мне отвечал каким-либо текстом

2024-09-29 12:22 UTC, sh4rkizz commented on simple-chat/index.html
> +    <header class="header">
немного смущает позиционирование хедера, особенно на десктопе
пользователя в центре видеть очень непривычно [justify-content: space-between]
![изображение](https://github.com/user-attachments/assets/ef41049d-fe1d-4e2f-97e3-611c38b8e49b)

2024-09-29 12:22 UTC, sh4rkizz commented on simple-chat/index.html
> +          </div>
Когда последняя строка сообщения занимает максимально возможную ширину в символах, дата уезжает куда-то

![изображение](https://github.com/user-attachments/assets/d5d2a66f-2555-455b-968b-8dbdb2a5e814)

2024-09-29 12:26 UTC, sh4rkizz commented
довольно принципиальная вещь : в шапке "Seen 1 hour ago", а в форме плейсхолдер "Введите сообщение"
предлагаю унифицировать используемый язык - какой хочешь, но оставить 1

2024-09-30 19:25 UTC, yarmkhlv commented on simple-chat/index.html
> +    <header class="header">
Привет, да особо не запаривался, как будет выглядеть после 600, в целом, хотел контейнером ограничить, но поленился, почему-то думал, что для мобилок достаточно будет.
В любом случае, потом добавится еще функционал и придётся перерассматривать уже написанные стили.
Хотелось бы узнать, какие брейкпоинты лучше использовать или чаще практикуют?
Обычно я использую :
планшеты от 600,
десктоп от 960,
лардж десктоп от 1280

2024-10-01 05:59 UTC, sh4rkizz approved these changes
lgtm!

2024-10-01 18:30 UTC, merged

2024-10-01 18:30 UTC, martinkomitsky commented
12!