Homework #3
yarmkhlv/2024-2-VK-EDU-Frontend-Y-Mikhailov pull request #3
Opened 2024-10-05 21:37 UTC by yarmkhlv

# Домашнее задание №3

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:

-Добавлена страница со списком чатов
-Реализован переход между страницами туда и обратно
-Сделал создание чата, чтобы работать с данными пользователей

Чтобы создать новый чат - нажмите на кнопку.
![image](https://github.com/user-attachments/assets/4e3e8111-3556-4f03-b6d2-cf792e1b582a)

2024-10-06 16:49 UTC, sh4rkizz approved these changes
Отличная работа, оствил несколько комментов, чтоб было полезно

2024-10-06 16:49 UTC, sh4rkizz commented on simple-chat/chat.html
> +                <img src="./src/assets/icons/more_vert.svg" alt="array" />
Давай поработаем с доступностью для людей с ограниченными возможностями

Картинки должны иметь alt, который явно описывает то, что на ней отображено.
Сейчас много мест, где повторяется alt="array", полагаю из-за копипаста, предлагаю поправить

2024-10-06 16:49 UTC, sh4rkizz commented on simple-chat/chat.html
> +      </section>
Давай также добавим стили для фокусировки элементов формы и различных кнопок хедера через TAB
здесь тебе поможет псевдокласс :focus-visible

<img width="707" alt="изображение" src="https://github.com/user-attachments/assets/1d25f3b4-4483-4731-bb52-a13667a7b8d0">

2024-10-06 16:49 UTC, sh4rkizz commented on simple-chat/src/css/components/header.scss
> +}
scss позволяет такие записи немного упрощать [не призываю править, просто fyi]
такая запись позволит читающему код сразу понять, что эти стили используются только внутри блока `.info-user`

```
.info-user {
  max-width: 200px;

  & > &__fio {
    color: var(--color-chat-name);
    font-weight: 600;

    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  & > &__entrytime {
    color: var(--color-neutral);
    font-weight: 500;
  }
}
```

2024-10-06 16:51 UTC, sh4rkizz commented
как думаешь, может стоит добавить что-то что визуально отделяет один чат от другого?

2024-10-06 16:54 UTC, sh4rkizz commented
Иногда залезает не очень приятно скроллбар, кажется не хватает padding или scrollbar-gutter

<img width="159" alt="изображение" src="https://github.com/user-attachments/assets/d7ba803e-7db0-43d8-85b0-2c4421ddf08a">

2024-10-06 16:56 UTC, sh4rkizz commented
Возможно полезно будет при открытии чата делать фокусировку на инпут

2024-10-06 17:03 UTC, sh4rkizz requested changes
Отличная работа, предлагаю поправить некоторые замечания

2024-10-07 20:28 UTC, yarmkhlv commented on simple-chat/src/css/components/header.scss
> +}
Вроде бы все исправил, кроме этого, пока подумаю, я как-то пробовал уже так писать, не особо зашло, потом, когда быстро какой-то стиль на проекте надо найти, приходится вручную вбивать нужный файл стилей и в нем искать, а так можно в глобальном поиске найти нужный стиль. Со вложенностью соглашусь, пока разбил на секции и в них вложил используемые стили.

2024-10-07 20:33 UTC, yarmkhlv commented
У меня всегда какие-то проблемы с декомпозицией файлов и написанием стилей, особенно, плохо получается стилизовать большие блоки, наподобие body, main, мне не нравится, что чтобы добиться нужного результата, приходиться в 3 дочерних компонента height:100% прокидывать, чтобы получить нужный результат, оттого кажется, что делаю что-то неправильно. 
Что-то в таком духе, хотелось бы по возможности исправить и научиться бест-практикам каким-то или обзавестись базой.

На это хотелось бы упор сделать больше.

2024-10-07 20:35 UTC, yarmkhlv commented
И не нравится то, что я могу в какой-то БЭМ начать писать, хотя не до конца его понимаю, но мне вроде и нужды в этом нет. Может мне достаточно однословно называть стили, наподобие, <<.entrytime>>, но просто вкладывать его?

![image](https://github.com/user-attachments/assets/bd62883d-102a-46a4-9724-916901519be4)

2024-10-10 11:20 UTC, sh4rkizz commented
Сломалась кнопочка добавления чатика

2024-10-13 12:26 UTC, sh4rkizz approved these changes
lgtm

2024-10-17 20:40 UTC, martinkomitsky commented
12!

2024-10-17 20:40 UTC, merged