Homework 5
yarmkhlv/2024-2-VK-EDU-Frontend-Y-Mikhailov pull request #6
Opened 2024-10-22 23:59 UTC by yarmkhlv

# Домашнее задание №5

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:

-Пересен чат на react
-Добавил модальное окно вместо промпта

2024-10-23 16:59 UTC, sh4rkizz requested changes
рекомендации в личке

2024-10-24 11:35 UTC, sh4rkizz requested changes

2024-10-24 11:35 UTC, sh4rkizz commented on react-chat/src/components/widgets/SectionChatList/SectionChatList.jsx
> +              onChange={(e) => setUserName(e.currentTarget.value)}
Предлагаю не делать перерендер на каждый символ
Давай повесим `ref` на `<input>` и в `handleClickBtnCreate` обрабатывать `ref.current`

2024-10-24 11:35 UTC, sh4rkizz commented on react-chat/src/components/widgets/SectionChatList/SectionChatList.jsx
> +    createNewChat(trimmedUserName);
Предлагаю запрещать создание чатов при пустом trimmedUserName

2024-10-24 11:35 UTC, sh4rkizz commented on react-chat/src/components/widgets/SectionChatList/SectionChatList.jsx
> +    createNewChat(trimmedUserName);
Если несложно, хотелось бы чтобы она и на enter отправлялась

2024-10-24 11:35 UTC, sh4rkizz commented on react-chat/src/components/widgets/SectionChatList/SectionChatList.jsx
> +    createNewChat(trimmedUserName);
хорошо что я под модалкой не могу скроллить, давай пойдем еще дальше
предлагаю чтобы фокус клавиатурой работал только в модалке, прилеплю ссылку с тем как это сделать

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert

<img width="766" alt="изображение" src="https://github.com/user-attachments/assets/ee3514e2-0fcb-4deb-b4fc-3b98226239b6">

2024-10-24 11:35 UTC, sh4rkizz commented on react-chat/src/components/widgets/SectionChatList/SectionChatList.jsx
> +    createNewChat(trimmedUserName);
кажется что не хватает каких-то выравниваний

<img width="59" alt="изображение" src="https://github.com/user-attachments/assets/7a9c5e27-8cd1-4494-a325-adbda7482de8">

2024-10-25 07:47 UTC, sh4rkizz approved these changes
lgtm !

2024-10-27 17:53 UTC, martinkomitsky commented
12!

2024-10-27 17:53 UTC, merged