Homework 6
yarmkhlv/2024-2-VK-EDU-Frontend-Y-Mikhailov pull request #7
Opened 2024-10-29 21:23 UTC by yarmkhlv

# Домашнее задание №6

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:

-Добавлен роутинг
-Сделана страница изменения профиля

2024-10-29 22:35 UTC, sh4rkizz requested changes

2024-10-29 22:35 UTC, sh4rkizz commented on react-chat/src/components/widgets/SectionEditProfile/SectionEditProfile.jsx
> +          <div className={styles.fieldName}>Имя пользователя</div>
это по идее `<label>`

2024-10-29 22:35 UTC, sh4rkizz commented on react-chat/src/components/widgets/SectionEditProfile/SectionEditProfile.jsx
> +    </section>
Мало кто любит автокомплиты на таких формах, давай срежем

<img width="763" alt="изображение" src="https://github.com/user-attachments/assets/fc6ec6d6-40f9-4322-9f00-14fcaf738758">

2024-10-29 22:35 UTC, sh4rkizz commented on react-chat/src/components/widgets/SectionEditProfile/SectionEditProfile.jsx
> +    </section>
Если устанавливаются ограничения, стоит о них сообщить пользователю какой-то подсказочкой, чтобы он это знал до того, как попытается отправить

<img width="351" alt="изображение" src="https://github.com/user-attachments/assets/800d01b5-c854-4a7a-acc8-c7476d8ac3b1">

2024-10-29 22:35 UTC, sh4rkizz commented on react-chat/src/components/widgets/SectionEditProfile/SectionEditProfile.jsx
> +export function SectionEditProfile({
На странице списка чатов `font-size: 18px`, в хедере ProfileEdit - `font-size: 16px`

2024-10-29 22:35 UTC, sh4rkizz commented on react-chat/src/components/widgets/SectionEditProfile/SectionEditProfile.jsx
> +export function SectionEditProfile({
давай для этой надписи `font-size: 14px;` поставим, а то она какая-то очень большая
<img width="273" alt="изображение" src="https://github.com/user-attachments/assets/30b7d3f4-f525-4f14-b168-400bfde9d7ad">

2024-10-29 22:35 UTC, sh4rkizz commented on react-chat/src/components/widgets/ChatItem/ChatItem.jsx
> +    <Link to={`/chat/:${id}`} tabIndex="-1">
А почему tabIndex="-1", мне кажется мы хотим, эти элементы фокусом обладали

2024-10-29 22:35 UTC, sh4rkizz commented on react-chat/src/components/widgets/SectionEditProfile/SectionEditProfile.jsx
> +          <div className={styles.fieldName}>Имя пользователя</div>
Мне с точки зрения доступности хотелось бы, чтобы когда я табов фокусируюсь на инпуте он имел рамочку

Возможно правильным решение будет спилить `outline: none` на `focus-visible` у `input`

<img width="763" alt="изображение" src="https://github.com/user-attachments/assets/25b75507-75cb-485e-b5dd-b24f566ac1fc">

2024-10-29 22:35 UTC, sh4rkizz commented on react-chat/src/components/widgets/SectionEditProfile/SectionEditProfile.jsx
> +          <div className={styles.fieldName}>Имя пользователя</div>
Немножно странно, что лейбл и плейсхолдер друг друга повторяют, но у меня нет идей как сделать правильнее

2024-10-29 22:35 UTC, sh4rkizz commented on react-chat/src/components/widgets/SectionEditProfile/SectionEditProfile.jsx
> +          <div className={styles.fieldName}>Имя пользователя</div>
\+ .trim()

<img width="264" alt="изображение" src="https://github.com/user-attachments/assets/2a89f87d-e72c-4520-b36e-6e00af7db9d6">

2024-10-29 22:35 UTC, sh4rkizz commented on react-chat/src/components/widgets/ChatItem/ChatItem.jsx
> +    <Link to={`/chat/:${id}`} tabIndex="-1">
Давай для чата намутим какую-нибудь обработку пустоты

<img width="849" alt="изображение" src="https://github.com/user-attachments/assets/8ada4549-b99f-43d8-8d8b-799303858c0b">

2024-10-30 22:52 UTC, sh4rkizz requested changes
отписал в личку по фокусам textarea + обработке ошибок

2024-11-01 09:14 UTC, sh4rkizz approved these changes
lgtm

2024-11-05 07:50 UTC, merged

2024-11-05 07:50 UTC, martinkomitsky commented
12!