homework 7
yarmkhlv/2024-2-VK-EDU-Frontend-Y-Mikhailov pull request #8
Opened 2024-11-17 15:06 UTC by yarmkhlv

# Домашнее задание №7

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано: интеграция API для работы с чатом.
-Создание пользователя
-Авторизация
-Редактирование пользователя
-Создание приватных чатов
-Отправка сообщений с использованием сокетов
-Реализована пагинация на скролл в сообщениях и в создании приватного чата, для получения новых данных

2024-11-18 21:01 UTC, sh4rkizz requested changes

2024-11-18 21:01 UTC, sh4rkizz commented on react-chat/src/components/widgets/SectionCreateUser/SectionCreateUser.jsx
> +  });
Пока ок без этого, но хотелось бы в будущем увидеть центрифугу и на странице со списком чатов

2024-11-21 07:55 UTC, sh4rkizz approved these changes
очень круто! lgtm

2024-11-24 12:37 UTC, merged

2024-11-24 12:38 UTC, martinkomitsky commented
10