homework 8
yarmkhlv/2024-2-VK-EDU-Frontend-Y-Mikhailov pull request #9
Opened 2024-11-27 19:40 UTC by yarmkhlv

# Домашнее задание №8

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:

-Добавлена возможность записи голосовых сообщений и их прослушивание
-Добавлена возможность загрузки изображений, а также их загрузка с использованием drag and drop
-Добавлена возможность передачи своего местоположения
-Добавлены уведомления, когда сообщения приходят из другого чата

2024-11-28 12:53 UTC, sh4rkizz requested changes

2024-11-28 12:53 UTC, sh4rkizz commented on react-chat/src/components/widgets/SectionInput/sectionInput.module.scss
> +  .attachItem {
В этом чате последним сообщением было отправлен фото
Визуально будто пустой чат, стоит добавить "Фото (<сколько прикреплено>)"

<img width="392" alt="изображение" src="https://github.com/user-attachments/assets/56f774da-7ca0-4f7b-a592-0f8c03568575">

2024-11-28 12:53 UTC, sh4rkizz commented on react-chat/src/components/widgets/SectionInput/sectionInput.module.scss
> +  .attachItem {
Аналогично с "Голосовое сообщение"

2024-11-28 12:53 UTC, sh4rkizz commented on react-chat/src/components/widgets/SectionInput/sectionInput.module.scss
> +  .attachItem {
Каждый запрос [блок catch] стоит дополнить toastify с "Что-то пошло не так"
Падал 5 минут на CORS запросах [полагаю проблема сервиса бекенда], при этом фронт молчал как партизан

2024-11-28 12:53 UTC, sh4rkizz commented on react-chat/src/components/widgets/SectionInput/sectionInput.module.scss
> +  .attachItem {
Крайне неприятно что выбрасывает из аккаунта при попытке создать ошибочный чат

<img width="552" alt="изображение" src="https://github.com/user-attachments/assets/e97e7162-05b2-4786-8566-150220c72c0a">

2024-11-28 12:53 UTC, sh4rkizz commented on react-chat/src/components/widgets/SectionInput/sectionInput.module.scss
> +  .attachItem {
На странице со списком чатов сломался скролл
Чатов гарантированно больше, чем я вижу на странице

2024-11-28 12:53 UTC, sh4rkizz commented on react-chat/src/components/widgets/SectionInput/sectionInput.module.scss
> +  .attachItem {
Было бы классно иметь функционал прикрепления текста к фотографиям

2024-11-30 21:36 UTC, sh4rkizz approved these changes
LGTM !

2024-12-06 22:14 UTC, HaseProgram commented
Класс, зачтено, 7!

2024-12-06 22:14 UTC, merged